Update hadoop to 3.2.0
prestodb/presto-hadoop-apache2 pull request #56
Opened 2022-04-01 16:04 UTC by rajatrj20

When presto runs on Hadoop 3 with `dfs.encrypt.data.transfer=true`, queries fails with error:

> com.facebook.presto.spi.PrestoException: Error committing write to Hive 
> 
> Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hadoop/a38381f4-fcc3-431d-bd73-bb0d872a1572/20211106_073946_00003_k9xuf_070809d7-6c9b-4d5f-ac17-86a998d2958d could only be written to 0 of the 1 minReplication nodes. There are 3 datanode(s) running and 3 node(s) are excluded in this operation.

and on HDFS side following error is thrown:
>javax.security.sasl.SaslException: Invalid token in javax.security.sasl.qop: 
    at com.sun.security.sasl.util.AbstractSaslImpl.parseProp(AbstractSaslImpl.java:242)
    at com.sun.security.sasl.util.AbstractSaslImpl.parseQop(AbstractSaslImpl.java:206)
    at com.sun.security.sasl.util.AbstractSaslImpl.parseQop(AbstractSaslImpl.java:197)
    at com.sun.security.sasl.util.AbstractSaslImpl.<init>(AbstractSaslImpl.java:73)
    at com.sun.security.sasl.digest.DigestMD5Base.<init>(DigestMD5Base.java:174)
    at com.sun.security.sasl.digest.DigestMD5Server.<init>(DigestMD5Server.java:145)
    at com.sun.security.sasl.digest.FactoryImpl.createSaslServer(FactoryImpl.java:109)
    at javax.security.sasl.Sasl.createSaslServer(Sasl.java:567)
    at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslParticipant.createServerSaslParticipant(SaslParticipant.java:66)
    at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.doSaslHandshake(SaslDataTransferServer.java:385)
    at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.getEncryptedStreams(SaslDataTransferServer.java:186)
    at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.receive(SaslDataTransferServer.java:118)
    at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:234)
    at java.lang.Thread.run(Thread.java:748)

This happens because presto still uses hadoop 2 libraries which results in failure when running on hadoop 3 system. This PR is to update support of hadoop 3 to presto engine by upgrading hadoop to version 3.2.0. This changes are not tested on hadoop 2 environment after updating it to hadoop 3 and if visibility is needed I can update that.

To add some historical context on how PrestoDB moved from hadoop-apache1 to hadoop-apache2, Presto was using hadoop-apache1 and then plugin for hadoop-apache2 was [added](https://github.com/prestodb/presto/pull/943) as well. After sometime plugin for hadoop-apache1 was [removed](https://github.com/prestodb/presto/pull/8213) from the dependencies and it started using only hadoop-apache2.
Also, Trino has moved away from hadoop 2 and is now on hadoop 3. Reference: [Update to Hadoop 3.2.0 #3](https://github.com/trinodb/trino-hadoop-apache/pull/3)

Ideally, we should also look at renaming this repository to **_presto-hadoop-apache_** to make it more generic or a new repository **_presto-hadoop-apache3_** should be created for hadoop version 3 the way repo [**_presto-hadoop-apache1_**](https://github.com/prestodb/presto-hadoop-apache1) and [**_presto-hadoop-apache2_** ](https://github.com/prestodb/presto-hadoop-apache2)already exist for version 1 and 2 respectively. Since, I am not sure which route needs to be taken, I didn't create or tried to rename the repository. Please let me know on the steps to be taken and I can follow those steps to do the further work required.

2022-04-01 16:07 UTC, rajatrj20 commented
@aweisberg @imjalpreet Please help reviewing this PR. I have opened this PR based on the feedback and comment from #53

2022-10-21 17:29 UTC, rajatrj20 commented
@imjalpreet, Could you please go through this CR?

2022-10-27 13:41 UTC, imjalpreet commented
@rajatrj20 Sorry for the delay, this PR completely got out of my mind. I will review it this week.

2022-12-26 14:10 UTC, imjalpreet commented
@rajatrj20 I will try to submit my review this week, got caught up in some other work for the past few weeks. Just carrying out some tests and after that will add my review.

2023-01-04 22:01 UTC, imjalpreet requested changes
@rajatrj20 Thanks for the contribution. Sorry for the long delay in reviewing this PR, I will try to fast-track it now. I have done a first pass and had a few comments. I will add more comments in case I have one. 

Also, have you carried out tests by including this updated dependency with Presto in your environment?

We would also need to plan on how we can introduce product/integration tests with Hadoop 3.x as well. Right now all the docker images used in the product tests are Hadoop 2.7.x.

2023-01-04 22:01 UTC, imjalpreet commented on src/main/java/org/apache/hadoop/fs/PrestoFileSystemCache.java
> +    public static final String PRESTO_S3_IAM_ROLE = "presto.s3.iam-role";
The string value for this variable was updated to `presto.hive.s3.iam-role` in master

2023-01-04 22:01 UTC, imjalpreet commented on src/main/resources/core-site.xml
> +<?xml version="1.0"?>
Do we still need this core-site file to be included with Hadoop 3 upgrade? As far as I know, this config was removed from Hadoop 3 onwards. This config was only required in some of the older versions, due to a bug which existed in Hadoop which was I think fixed with Hadoop 3.

2023-01-31 19:53 UTC, rohanpednekar commented
@rajatrj20 Thanks for your contributions, do you think you can address the feedback, so we can target this feature for the next release?

2023-02-01 05:03 UTC, rajatrj20 commented
@imjalpreet thanks for the feedback. Will work on this and update.

2023-02-03 17:00 UTC, rajatrj20 commented on src/main/java/org/apache/hadoop/fs/PrestoFileSystemCache.java
> +    public static final String PRESTO_S3_IAM_ROLE = "presto.s3.iam-role";
Updated it.

2023-02-03 17:01 UTC, rajatrj20 commented on src/main/resources/core-site.xml
> +<?xml version="1.0"?>
Yes, this is no longer required and I have removed it.

2023-02-03 17:04 UTC, rajatrj20 commented
> @rajatrj20 Thanks for the contribution. Sorry for the long delay in reviewing this PR, I will try to fast-track it now. I have done a first pass and had a few comments. I will add more comments in case I have one.
> 
> Also, have you carried out tests by including this updated dependency with Presto in your environment?
> 
> We would also need to plan on how we can introduce product/integration tests with Hadoop 3.x as well. Right now all the docker images used in the product tests are Hadoop 2.7.x.

I have run basic product tests by including this updated dependency and they are passing.

Yes, we will need to docker images to use updated version of Hadoop and other dependencies after this upgrade.

2023-02-23 05:02 UTC, rajatrj20 commented
@imjalpreet, just following up on the review. Please help review updated changes.

2023-03-29 07:00 UTC, imjalpreet requested changes
@rajatrj20 thanks for the changes, a few more minor comments, let me know if you have any questions.

2023-03-29 07:00 UTC, imjalpreet commented on src/main/java/org/apache/hadoop/crypto/key/kms/KMSClientProvider.java
@rajatrj20 I see this file has a lot of code style and indentation changes. Can we revert them for this PR?

2023-03-29 07:00 UTC, imjalpreet commented on src/main/resources/nativelib/Linux-amd64/libhadoop.so
Just wanted to get an idea here, have you generated these native libraries yourself by building Hadoop since they have been modified?

2023-03-29 07:05 UTC, rajatrj20 commented on src/main/resources/nativelib/Linux-amd64/libhadoop.so
No, I have taken them from the PR: https://github.com/trinodb/trino-hadoop-apache/pull/3

2023-03-29 10:56 UTC, imjalpreet commented on src/main/resources/nativelib/Linux-amd64/libzstd.so
Forgot to mention, let's keep the permissions as 755 itself which were set earlier.

2023-03-29 13:33 UTC, rajatrj20 commented on src/main/resources/nativelib/Linux-amd64/libzstd.so
Removed checkstyle changes and changed permission to the previous state.

2023-04-10 08:56 UTC, rajatrj20 commented
@imjalpreet can you please review the changes.

2023-06-26 08:45 UTC, imjalpreet approved these changes
LGTM 👍🏼

2023-06-26 09:34 UTC, rajatrj20 commented
> LGTM 👍🏼

Thanks for reviewing. I don't have permission to merge this. Could you please merge this?

2023-07-19 11:57 UTC, rajatrj20 commented
@imjalpreet Can we please get this merged?

2023-07-20 20:33 UTC, imjalpreet commented
@tdcmeehan can you please do a final review? If you believe there is someone else who should also do a round of review, please add. Thanks.

2023-07-31 14:20 UTC, tdcmeehan approved these changes

2023-07-31 14:20 UTC, merged